[package]
name = "readable"
version = "0.4.0"
edition = "2021"
authors = ["hinto.janai <hinto.janai@protonmail.com>"]
description = "Human readable data formatting"
documentation = "https://docs.rs/readable"
repository = "https://github.com/hinto-janai/readable"
readme = "README.md"
keywords = ["human", "readable", "data", "read", "string"]
license = "MIT"

[package.metadata.docs.rs]
all-features = true

[features]
default = []
ignore_nan_inf = []

[dependencies]
compact_str = { version = "0.7.0", features = ["bytes", "serde"] }
num-format = "0.4.4"
serde = { version = "1.0.159", features = ["derive"], optional = true }
