[package]
name = "readable"
version = "0.5.0"
edition = "2021"
authors = ["hinto.janai <hinto.janai@protonmail.com>"]
description = "Human readable data formatting"
documentation = "https://docs.rs/readable"
repository = "https://github.com/hinto-janai/readable"
readme = "README.md"
keywords = ["human", "readable", "data", "read", "string"]
license = "MIT"

[package.metadata.docs.rs]
all-features = true

[features]
default = []
full    = ["serde", "ignore_nan_inf"]
ignore_nan_inf = []

[dependencies]
atoi = "2.0.0"
chrono      = { version = "0.4.24", features = ["serde"] }
compact_str = { version = "0.7.0", features = ["bytes", "serde"] }
lazy_static = { version = "1.4.0" }
lexical = "6.1.1"
lexical-parse-integer = "0.8.6"
num-format  = { version = "0.4.4", features = ["with-serde"] }
regex       = { version = "1.7.3" }
serde       = { version = "1.0.159", features = ["derive"], optional = true }
