[package]
name = "readable"
version = "0.7.7"
edition = "2021"
authors = ["hinto.janai <hinto.janai@protonmail.com>"]
description = "Human readable data formatting"
documentation = "https://docs.rs/readable"
repository = "https://github.com/hinto-janai/readable"
readme = "README.md"
keywords = ["human", "readable", "data", "read", "string"]
license = "MIT"

[package.metadata.docs.rs]
all-features = true

[features]
default        = []
full           = ["serde", "ignore_nan_inf", "inline_date", "inline_time", "inline_runtime"]
ignore_nan_inf = []
inline_date    = ["readable-inlined-date"]
inline_time    = ["readable-inlined-time"]
inline_runtime = ["readable-inlined-runtime"]
#inline_percent = ["readable-inlined-percent"]

[dependencies]
inherent    = "1.0.7"
paste       = "1.0.12"
seq-macro   = "0.3.3"
compact_str = { version = "0.7.0", features = ["bytes", "serde"] }
lazy_static = { version = "1.4.0" }
num-format  = { version = "0.4.4", git = "https://github.com/hinto-janai/num-format.git", features = ["with-serde"] }
regex       = { version = "1.8.1" }
serde       = { version = "1.0.160", features = ["derive"], optional = true }

# Inlined crates.
readable-inlined-date    = { version = "0.1.1", optional = true }
readable-inlined-time    = { version = "0.1.0", optional = true }
readable-inlined-runtime = { version = "0.1.0", optional = true }
#readable-inlined-percent = { version = "0.1.0", optional = true }
