[package]
name = "readable"
version = "0.6.3"
edition = "2021"
authors = ["hinto.janai <hinto.janai@protonmail.com>"]
description = "Human readable data formatting"
documentation = "https://docs.rs/readable"
repository = "https://github.com/hinto-janai/readable"
readme = "README.md"
keywords = ["human", "readable", "data", "read", "string"]
license = "MIT"

[package.metadata.docs.rs]
all-features = true

[features]
default        = []
full           = ["serde", "ignore_nan_inf", "inline_time", "inline_runtime"]
ignore_nan_inf = []
inline_time    = []
inline_runtime = []

[dependencies]
paste       = "1.0.12"
seq-macro   = "0.3.3"
compact_str = { version = "0.7.0", features = ["bytes", "serde"] }
lazy_static = { version = "1.4.0" }
num-format  = { version = "0.4.4", features = ["with-serde"] }
regex       = { version = "1.7.3" }
serde       = { version = "1.0.159", features = ["derive"], optional = true }
