# This clippys, docs, tests, builds.

name: macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - name: Cache
      uses: actions/cache@v3.2.3
      with:
        path: |
          ~/.cargo
          target
        key: macos
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Clippy
      run: cargo clippy --all-features
    - name: Doc
      env:
        RUSTFLAGS: '-D warnings'
      run: cargo doc --workspace --no-deps --all-features
    - name: Test
      # GitHub actions has weird behavior with `f64::NAN`.
      # This test works normally locally.
      run: cargo test --all-features -- --skip "float::tests::special" --skip "int::tests::special"
    - name: Build
      run: cargo build --all-features
